name: build-and-push-prose-app
on: [push]
jobs:
    build-and-push:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout source code from git repository
          uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.24'

        - name: Show go version (debug)
          run: go version

        - name: Print working directory
          run: pwd

        - name: Build
          run: go build -o artifact/prose-app.exe